//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Products.Properties
{


    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string BackupFolder
        {
            get
            {
                return ((string)(this["BackupFolder"]));
            }
            set
            {
                this["BackupFolder"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool PaidMonth
        {
            get
            {
                return ((bool)(this["PaidMonth"]));
            }
            set
            {
                this["PaidMonth"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool PaidYear
        {
            get
            {
                return ((bool)(this["PaidYear"]));
            }
            set
            {
                this["PaidYear"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool PaidEver
        {
            get
            {
                return ((bool)(this["PaidEver"]));
            }
            set
            {
                this["PaidEver"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public DateTime setupDate
        {
            get
            {
                return ((DateTime)(this["setupDate"]));
            }
            set
            {
                this["setupDate"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool firstTimeUse
        {
            get
            {
                return ((bool)(this["firstTimeUse"]));
            }
            set
            {
                this["firstTimeUse"] = value;
            }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [SpecialSetting(SpecialSetting.ConnectionString)]
        [DefaultSettingValue("Data Source=ESLAMMAHFOUZ;Initial Catalog=Products;Integrated Security=True")]
        public string ProductsConnectionString
        {
            get
            {
                return ((string)(this["ProductsConnectionString"]));
            }
        }
    }
}
