//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Sales = new HashSet<Sale>();
            this.SalesPayments = new HashSet<SalesPayment>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerTel { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<double> CustomerCharge { get; set; }
    
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<SalesPayment> SalesPayments { get; set; }
    }
}
