//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.PurchasesDetails = new HashSet<PurchasesDetail>();
            this.PurchasesPayments = new HashSet<PurchasesPayment>();
        }
    
        public int PurchaseID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> PurchaseDiscount { get; set; }
        public Nullable<double> PurchaseNetPrice { get; set; }
        public Nullable<double> PurchasePaid { get; set; }
        public Nullable<double> PurchaseCharge { get; set; }
        public int SupplierID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<PurchasesDetail> PurchasesDetails { get; set; }
        public virtual ICollection<PurchasesPayment> PurchasesPayments { get; set; }
    }
}
