//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasesPayment
    {
        public int PurchasePayID { get; set; }
        public int PurchaseID { get; set; }
        public Nullable<double> PurchasePayPaid { get; set; }
        public Nullable<double> PurchasePayCharge { get; set; }
        public Nullable<System.DateTime> PurchasePayDate { get; set; }
    
        public virtual Purchase Purchase { get; set; }
    }
}
