//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Purchases = new HashSet<Purchase>();
            this.PurchasesPayments = new HashSet<PurchasesPayment>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierPhone { get; set; }
        public string SupplierTel { get; set; }
        public string SupplierAddress { get; set; }
        public Nullable<double> SupplierCharge { get; set; }
    
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual ICollection<PurchasesPayment> PurchasesPayments { get; set; }
    }
}
