//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dukan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasePayment
    {
        public int Id { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public decimal Paid { get; set; }
        public string Type { get; set; }
    
        public virtual Purchase Purchase { get; set; }
    }
}
