//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dukan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        public int Id { get; set; }
        public int SaleId { get; set; }
        public int ProductId { get; set; }
        public double ProductBuy { get; set; }
        public double ProductSell { get; set; }
        public int Qte { get; set; }
        public double Discount { get; set; }
        public int ReturnedQte { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
